apiVersion: v1
kind: Namespace
metadata:
  name: python

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: python-serviceaccount
  namespace: python

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: python
  name: pod-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---

# create roleBinding

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-reader-binding
  namespace: python
roleRef: # points to the Role
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-reader # name of Role
subjects: # points to the ServiceAccount
- kind: ServiceAccount
  name: python-serviceaccount # service account to bind to
  namespace: python # ns of service account